create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  project_number text not null,
  title text not null,
  category text not null,
  description text not null,
  technologies text[] not null default '{}',
  image text,
  link text,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.projects
  add column if not exists project_number text,
  add column if not exists title text,
  add column if not exists category text,
  add column if not exists description text,
  add column if not exists technologies text[] not null default '{}',
  add column if not exists image text,
  add column if not exists link text,
  add column if not exists featured boolean not null default false,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.skills
  add column if not exists id bigint generated by default as identity,
  add column if not exists sort_order integer not null default 0,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists skills_set_updated_at on public.skills;
create trigger skills_set_updated_at
before update on public.skills
for each row execute function public.set_updated_at();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(nullif(excluded.full_name, ''), public.profiles.full_name);

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_auth_user();

insert into public.profiles (id, email, full_name)
select
  users.id,
  users.email,
  coalesce(users.raw_user_meta_data ->> 'full_name', '')
from auth.users as users
on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(nullif(excluded.full_name, ''), public.profiles.full_name);

alter table public.projects enable row level security;
alter table public.skills enable row level security;
alter table public.profiles enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.projects to anon, authenticated;
grant insert, update, delete on public.projects to authenticated;
grant select on public.skills to anon, authenticated;
grant insert, update, delete on public.skills to authenticated;
grant select on public.profiles to authenticated;

do $$
declare
  projects_sequence text;
begin
  projects_sequence := pg_get_serial_sequence('public.projects', 'id');
  if projects_sequence is not null then
    execute format('grant usage, select on sequence %s to authenticated', projects_sequence);
  end if;
end;
$$;

drop policy if exists "projects are readable by everyone" on public.projects;
create policy "projects are readable by everyone"
on public.projects for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert projects" on public.projects;
drop policy if exists "authenticated users can insert projects" on public.projects;
create policy "authenticated users can insert projects"
on public.projects for insert
to authenticated
with check (true);

drop policy if exists "admins can update projects" on public.projects;
drop policy if exists "authenticated users can update projects" on public.projects;
create policy "authenticated users can update projects"
on public.projects for update
to authenticated
using (true)
with check (true);

drop policy if exists "admins can delete projects" on public.projects;
drop policy if exists "authenticated users can delete projects" on public.projects;
create policy "authenticated users can delete projects"
on public.projects for delete
to authenticated
using (true);

drop policy if exists "skills are readable by everyone" on public.skills;
create policy "skills are readable by everyone"
on public.skills for select
to anon, authenticated
using (true);

drop policy if exists "authenticated users can insert skills" on public.skills;
create policy "authenticated users can insert skills"
on public.skills for insert
to authenticated
with check (true);

drop policy if exists "authenticated users can update skills" on public.skills;
create policy "authenticated users can update skills"
on public.skills for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated users can delete skills" on public.skills;
create policy "authenticated users can delete skills"
on public.skills for delete
to authenticated
using (true);

drop policy if exists "users can read their own profile" on public.profiles;
create policy "users can read their own profile"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

-- Create the Supabase Auth user first, then promote that account in the SQL editor:
-- update public.profiles set role = 'admin' where email = 'admin@example.com';